---
- name: Подключение Стандартного файла деплой
  include: "nginx_deploy.yml"
  vars:
    name: nginx
    templates:
    - docker-compose.yml
    configs:
    - jenkins.conf
    - registry.conf
  tags:
    - nginx
