---
- name: Копирование сертификатов
  copy:
    src: "../../common/files/certs"
    dest: "/home/ybd/registry"
  
- name: Подключение Стандартного файла деплой
  include: "../common/default_deploy.yml"
  vars:
    name: registry
    templates:
    - docker-compose.yml
  tags:
    - registry
