- hosts: tst
  remote_user: ybd
  roles:
    - { role: preconfig, tags: ['preconfig'] }
    - { role: jenkins }
    - { role: keycloak, tags: ['keycloak']  }

- hosts: nginx
  remote_user: ybd
  roles:
    - { role: nginx, tags: ['nginx'] }

- hosts: ipa
  remote_user: ybd
  roles:
    - { role: ipa, tags: ['ipa'] }