- hosts: preconfig
  remote_user: it
  roles:
    - { role: preconfig, tags: ['preconfig'] }

- hosts: nginx
  remote_user: ybd
  roles:
    - { role: nginx, tags: ['nginx'] }

- hosts: ipa
  remote_user: ybd
  roles:
    - { role: ipa, tags: ['ipa'] }

- hosts: registry
  remote_user: ybd  
  roles:
    - { role: registry, tags: ['registry'] }