---
- name: Добавляем пользователей
  include: "user.yml"
  vars: 
    user: "{{ item }}"
  loop: "{{ users }}"
    
- name: Установка docker и docker-compose
  become: true 
  block:
  - name: Добавляем universe
    apt_repository:
      repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
      state: present 
   
  - name: Установка дополнительных пакетов
    apt:
      name: '{{ apt.packages }}'
      update_cache: true
      cache_valid_time: 86400

  - name: Добавление ключа Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
      keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    
  - name: Установка стабильного репозитория
    apt_repository:
      repo: >
        deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
        https://download.docker.com/linux/ubuntu
        {{ ansible_distribution_release }} stable
      state: present
      update-cache: true
      filename: docker

  - name: Установка Docker-ce
    apt:
      name: docker-ce
      update-cache: true
  
  - name: Проверка что Docker установлен и перезагружен
    service:
      name: docker
      state: restarted
      enabled: true

  - name: Получение последней версии Docker-compose
    uri:
      url: https://api.github.com/repos/docker/compose/releases/latest
      body_format: json
    register: page
 
  - name: Установка Docker-compose
    get_url:
      url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-linux-x86_64"
      dest: /usr/local/bin/docker-compose

  - name: Установка дополнительных пакетов python
    pip:
      name: '{{ python.packages }}'

  - name: Добавление пользователя в группу docker и sudo
    user: 
      name: '{{ item.name }}'
      groups:
      - docker
      - sudo
      append: yes
    loop: "{{ sudousers }}"
      
  tags:
    - docker_install

- name: Установка timezone
  become: true
  timezone:
    name: Europe/Moscow

- name: Перезагрузка
  become: true
  reboot:
    msg: "Rebooting after preconfig"