---
- name: Пользователь с правами sudo
  become: true
  block:
  - name: Добавляем пользователя
    user: 
      name: "{{ user.name }}"
      shell: /bin/bash
      append: true

  - name: Добавляем ключ в authorized_keys
    authorized_key: user="{{ user.name }}" key="{{ user.key }}"

  - name: Добавляем пользователя в sudoers
    template:
      src: "sudoers/user.j2"
      dest: /etc/sudoers.d/{{ user.name }}
      mode: 0440
  tags:
    - user_add

    